server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ecommerceapi
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/ecommerceapi/**
eureka:
  client:
    register-with-eureka: false